initrd-setup-root: Drop workarounds for systemd <259
We are updating systemd to 259, so these are not necessary anymore.

Signed-off-by: Krzesimir Nowak <knowak@microsoft.com>

diff --git a/dracut/99setup-root/initrd-setup-root b/dracut/99setup-root/initrd-setup-root
--- a/dracut/99setup-root/initrd-setup-root
+++ b/dracut/99setup-root/initrd-setup-root
@@ -32,8 +32,8 @@ COREOS_BLANK_MACHINE_ID="42000000000000000000000000000042"
 MACHINE_ID_FILE="/sysroot/etc/machine-id"
 
 # Allow to rerun the script
-if SYSTEMD_IN_INITRD=0 systemd-confext --root=/sysroot status | grep flatcar-default; then
-  SYSTEMD_IN_INITRD=0 systemd-confext --root=/sysroot unmerge
+if systemd-confext --root=/sysroot status | grep flatcar-default; then
+  systemd-confext --root=/sysroot unmerge
 fi
 
 function selectiveosreset() {
@@ -165,10 +165,8 @@ mkdir -p /sysroot/var/lib/extensions.mutable/
 if [ ! -L /sysroot/var/lib/extensions.mutable/etc ] && [ ! -e /sysroot/var/lib/extensions.mutable/etc ]; then
   ln -s /etc /sysroot/var/lib/extensions.mutable/etc
 fi
-# Workaround until 259: Set SYSTEMD_IN_INITRD because even with --root=
-# this would otherwise look for initrd extension metadata.
-SYSTEMD_IN_INITRD=0 systemd-confext --root=/sysroot merge
-SYSTEMD_IN_INITRD=0 systemd-confext --root=/sysroot status | grep flatcar-default || { echo "error: flatcar-default confext not loaded" ; exit 1 ; }
+systemd-confext --root=/sysroot merge
+systemd-confext --root=/sysroot status | grep flatcar-default || { echo "error: flatcar-default confext not loaded" ; exit 1 ; }
 # Even when the planned sysext/confext .services units are there
 # the above call should stay because we first need confext for Ignition
 # to have default files but then we need to reload for any user confexts
